org.slf4j.simpleLogger.defaultLogLevel=WARN
org.slf4j.simpleLogger.log.org.apache.kafka.streams=INFO
org.slf4j.simpleLogger.log.org.apache.kafka.streams.StreamsConfig=WARN
org.slf4j.simpleLogger.log.org.apache.kafka.clients.admin.AdminClientConfig=WARN
org.slf4j.simpleLogger.log.org.apache.kafka.clients.consumer.ConsumerConfig=WARN
org.slf4j.simpleLogger.log.org.apache.kafka.clients.producer.ProducerConfig=WARN
org.slf4j.simpleLogger.log.org.apache.kafka.common.utils.AppInfoParser=WARN
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS
org.slf4j.simpleLogger.showThreadName=false
